// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdkjwwsgwedjqplovcts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZka2p3d3Nnd2VkanFwbG92Y3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODE3MjIsImV4cCI6MjA2OTM1NzcyMn0.OQD1tWACSypOFtN6HbG_N-eDZFrP_x3vq9JBNb6Himw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});